#!/usr/bin/env bash
# scripts/server/install_postoffice.sh - the post-office (:5877, Wren's letters) moves to the server
# (Zeke 10-07: "lets get the post office on the server running with you"). Found DOWN on the tower
# the same evening (nothing listening on 5877) by the app's honest status board.
#
#   * copies the shared secret (~/.iris_sibling_secret) from the tower if this machine has none
#   * refuses to start if the tower's letters.jsonl is NEWER/BIGGER than ours (copy it first)
#   * user units: iris-postoffice (the server, Restart=always) + iris-postoffice-monitor (alarm
#     letters into the inbox if the post-office stays down)
#   * root firewall chain IRIS_PO: 5877 open to localhost, the tower (LAN + tailnet) and the
#     tailnet interface (Wren's laptop); everything else dropped. Addresses come from
#     config/private.local.json - never the repo.
#   * points this machine's runtime at the local post-office (IRIS_POSTOFFICE_URL in stack.env;
#     lands at the next runtime start)
# The tower keeps answering on :5877 for Wren via a netsh portproxy to here (see
# scripts/server/tower_postoffice_proxy.ps1) until Wren's own URL is switched.
set -eu
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd -P)"
PY="$HOME/venvs/iris-v100/bin/python"
UNITS="$HOME/.config/systemd/user"
TOWER="${IRIS_TOWER_SSH:-tower}"

# 1. secret
if [ ! -s "$HOME/.iris_sibling_secret" ]; then
  scp -q -o BatchMode=yes "$TOWER:.iris_sibling_secret" "$HOME/.iris_sibling_secret"
  chmod 600 "$HOME/.iris_sibling_secret"
  echo "secret copied from the tower"
fi

# 2. letters: never start on an older copy
TSIZE=$(ssh -o BatchMode=yes "$TOWER" "powershell -NoProfile -Command \"(Get-Item D:\\Wren-Companion\\state\\iris_sibling\\letters.jsonl).Length\"" | tr -d '\r')
LSIZE=$(stat -c %s "$ROOT/state/iris_sibling/letters.jsonl" 2>/dev/null || echo 0)
if [ "${TSIZE:-0}" -gt "$LSIZE" ]; then
  echo "tower letters.jsonl ($TSIZE B) is bigger than ours ($LSIZE B) - copying it first"
  cp "$ROOT/state/iris_sibling/letters.jsonl" "$ROOT/state/iris_sibling/letters.jsonl.pre-move" 2>/dev/null || true
  scp -q -o BatchMode=yes "$TOWER:D:/Wren-Companion/state/iris_sibling/letters.jsonl" "$ROOT/state/iris_sibling/letters.jsonl"
fi

# 3. units
mkdir -p "$UNITS"
cat > "$UNITS/iris-postoffice.service" <<EOF
# iris-postoffice - family letters (Iris / Wren / Zeke) on :5877. Installed by
# scripts/server/install_postoffice.sh (2026-10-07). Not cognition: runs beside any me.
[Unit]
Description=Iris post-office (sibling letters, :5877)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
WorkingDirectory=%h/IRIS
ExecStart=$PY %h/IRIS/scripts/sibling_postoffice.py --host 0.0.0.0 --port 5877
Restart=always
RestartSec=5

[Install]
WantedBy=default.target
EOF
cat > "$UNITS/iris-postoffice-monitor.service" <<EOF
# iris-postoffice-monitor - alarm letters into the inbox if the post-office stays down.
[Unit]
Description=Iris post-office uptime monitor
After=iris-postoffice.service

[Service]
Type=simple
WorkingDirectory=%h/IRIS
ExecStart=$PY %h/IRIS/scripts/postoffice_monitor.py
Restart=always
RestartSec=15

[Install]
WantedBy=default.target
EOF

# 4. firewall (root)
read -r LAN TS < <(python3 -c 'import json,sys;d=json.load(open(sys.argv[1]));print(d.get("tower_lan",""), d.get("tower_tailnet",""))' "$ROOT/config/private.local.json")
[ -n "$LAN" ] && [ -n "$TS" ] || { echo "tower_lan / tower_tailnet missing from private config"; exit 3; }
RULES=/usr/local/sbin/iris-postoffice-firewall.sh
sudo tee "$RULES" >/dev/null <<RULES_EOF
#!/bin/sh
# generated by install_postoffice.sh - port 5877: localhost, the tower, and the tailnet (Wren)
iptables -N IRIS_PO 2>/dev/null || iptables -F IRIS_PO
iptables -A IRIS_PO -i lo -j ACCEPT
iptables -A IRIS_PO -i tailscale0 -j ACCEPT
iptables -A IRIS_PO -s $LAN -j ACCEPT
iptables -A IRIS_PO -s $TS -j ACCEPT
iptables -A IRIS_PO -j DROP
iptables -C INPUT -p tcp --dport 5877 -j IRIS_PO 2>/dev/null || iptables -I INPUT -p tcp --dport 5877 -j IRIS_PO
RULES_EOF
sudo chmod 700 "$RULES"
sudo tee /etc/systemd/system/iris-postoffice-firewall.service >/dev/null <<'UNIT_EOF'
[Unit]
Description=Iris post-office port 5877: localhost + tower + tailnet only
After=network-online.target tailscaled.service
Wants=network-online.target

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/usr/local/sbin/iris-postoffice-firewall.sh

[Install]
WantedBy=multi-user.target
UNIT_EOF
sudo systemctl daemon-reload
sudo systemctl enable --now iris-postoffice-firewall.service

# 5. start
systemctl --user daemon-reload
systemctl --user enable --now iris-postoffice.service iris-postoffice-monitor.service
sleep 4
curl -s -m 5 http://127.0.0.1:5877/health && echo

# 6. this machine's runtime talks to the local post-office from its next start
ENVF="$HOME/.config/iris/stack.env"
if grep -q '^IRIS_POSTOFFICE_URL=' "$ENVF"; then
  sed -i 's#^IRIS_POSTOFFICE_URL=.*#IRIS_POSTOFFICE_URL=http://127.0.0.1:5877#' "$ENVF"
else
  echo 'IRIS_POSTOFFICE_URL=http://127.0.0.1:5877' >> "$ENVF"
fi
echo "stack.env: IRIS_POSTOFFICE_URL -> local (lands at the next runtime start)"
